NCN-104143: Move yamls to pre-install under nkp-nutanix-product-catalog
nutanix-cloud-native/nkp-nutanix-product-catalog pull request #24
Opened 2024-11-13 05:07 UTC by johnliu25

Move kserve and nai-self-signed-cert yamls to pre-install under nkp-nutanix-product-catalog

2024-11-14 16:54 UTC, cwyl02 submitted a review, later dismissed

2024-11-14 21:31 UTC, takirala requested changes
Why are we moving a helmrelease (https://github.com/nutanix-cloud-native/nkp-nutanix-product-catalog/blob/NCN-104143/services/nutanix-ai/2.0.0/pre-install/kserve.yaml) outside of `helmreleases` dir and into a `pre-install` directory ? `pre-install` is supposed to (conventionally) host short lived jobs and not long lived helmreleases. think of `pre-install` as similar to helm hooks like `pre-upgrade` `post-upgrade` `post-install` etc., they are all short lived tasks.

2024-11-14 21:34 UTC, johnliu25 commented
@takirala thanks for your comment. I just move all the components as the prerequisite of the NAI deployment into the pre-install directory to identify them as the component need to pre-installed before NAI.

2024-11-14 21:42 UTC, takirala commented
@johnliu25 lets seperate the short lived and long running resources please, current structure might be hard to maintain in future when we work on upgrades and such. 

```
- helmreleases # dir for hosting helmreleases
- prerequisits # dir for knative helmreleases
- pre-install # dir for short lived tasks
```

2024-11-15 19:28 UTC, takirala approved these changes

2024-11-15 19:33 UTC, cwyl02 approved these changes

2024-11-15 21:16 UTC, merged